# Only for local development

version: "3.8"

services:
  mysql:
    extends:
      file: mysql/docker-compose.yml
      service: mysql
    networks:
      - backend-network
    volumes:
      - my-db:/var/lib/mysql

  backend:
    build: ./
    ports:
      - "3000:3000"
    networks:
      - backend-network
    environment:
      DATABASE_URL: mysql://admin:password@mysql:3306/db?schema=public
      MULTER_DEST: ./upload
    links:
      - mysql

volumes:
  my-db:

networks:
  backend-network:
